### PR TITLE
Make it easier to work with tabs in cypress

### PR DESCRIPTION
**Pull request by siemiatj**
Related to #1926

### CODE REVIEW

**Comment by siemiatj** [comment]
@metas-ts it's a really generic thing so I don't think creating a custom command makes sense. It should just work like this:

`cy.get('#internalName').click()`. 

But I just realized I added the id on the tab for selecting, and not the pill for clicking. Let me fix that.

**Comment by siemiatj** [comment]
screen shot 2018-09-19 at 09 48 05

**Comment by metas-ts** [comment]
>  It should just work like this:
> 
> cy.get('#internalName').click().

That's particularly great @siemiatj , buuut, afaiu that makes it really important to have the `tab_` prefix
I.e. afaiu we need to have 
`cy.get('tab_#internalName').click();`

to avoid colision with unrelated elements from a different part of the application dictionary that just happen to have the same `#internalName`

wdyt?

**Comment by siemiatj** [comment]
Yeah, makes sense. And then creating a custom command makes sense as well :)

**Pull request merged**
