### PR TITLE
Cleanup selections logic

### PR DESCRIPTION
**Pull request by siemiatj**
Trying to make some sense of selections in Tables. Also added a small helper for getting quickActions.

Related to #2693

### CODE REVIEW

**Comment by petrican** [comment]
Pls try to fix the selections when you switch back from right to left panels and make sure the selection is made by default when you select on the right with either first if no previous selection is done or last from the left side if there was an already made selection. https://github.com/metasfresh/me03/issues/4490#issuecomment-617593564. 

Would have been nice to have this in a table reducer as we are currently planning but I don't think there is enough time for such refactoring now.

Like:
table {
    active_selections: {
          [viewId_tabID] : rowId
    } 
}

This way you would know anytime what is selected and where.

**Comment by siemiatj** [comment]
So the related e2e tests seem to pass now : https://dashboard.cypress.io/projects/5yp4q1/runs/745/specs . Some other stuff failed, looks to be mostly a timing issue or something.

**Comment by petrican** [comment]
Yeah picking/pick_HUs_and_create_shipment.js was the one failing as a result of bad selection.
The others tests are failing due to something else. Dunno. Might be what Tobi said he merged. Anyways will check those starting next week

**Comment by petrican** [comment]
Lgtm. Cypress suite that used to work is passing now. Good job!

**Pull request merged**
