### PR TITLE
1945-frontend - About section

### PR DESCRIPTION
**Pull request by siemiatj**
Related to #1945

### CODE REVIEW

**Comment by siemiatj** [comment]
Getting subrows changelog works, but there's no indication of that and because it may have the same creator and date it looks like it doesn't.

main
screen shot 2019-01-18 at 17 13 50


subrow
screen shot 2019-01-18 at 17 14 08

**Comment by metas-mk** [comment]
> Getting subrows changelog works, but there's no indication of that and because it may have the same creator and date it looks like it doesn't.
> 
> main
> screen shot 2019-01-18 at 17 13 50
> 
> subrow
> screen shot 2019-01-18 at 17 14 08

@siemiatj 
Only one of both are show. The about data for main view OR the about data for subtab.

The requirement wanted to see both of a subtab row is selected.

> created, created by, updated, updateby of main record
> created, created by, updated, updateby of selected sub record (if selected)

Can you please fix.

**Comment by siemiatj** [comment]
@metas-mk Ready for a re-test.

**Comment by siemiatj** [comment]
Ready for a review.

**Pull request merged**
