### PR TITLE
Use community standards for prettier linting rules

### PR DESCRIPTION
**Pull request by siemiatj**
Some of the settings were... weird. This should make contributions easier.  Plus switching to use `classnames` library for handling element's class names.

### CODE REVIEW

**Comment by PabloSichert** [comment]
Hey @siemiatj, I think you somewhat missed the point of using prettier.

Its main use is being able to _automatically_ enforce a style and keeping the whole code base consistent with that. We deliberately chose the default options since there will always be a rule to disagree with.

Now, the good thing is - you can write the code as you want and automatically transform it to the "correct" rules by simply saving the file.

Did you by chance not use any integration with prettier in your code editor? E.g. https://atom.io/packages/prettier-atom

For the same reasons its also essential to keep the rules as `"error"` instead of `"warn"` so that the CI keeps track of the code being consistent.

If you want to globally change options, you need to run `yarn lint --fix` and everything will be transformed. Note that this way we lose a lot of `git blame` information.

I know it can be annoying it times, but it would be nice if you could open an issue first before submitting a PR. That way it could have been explained.

If you want, we can go from `"`to `'`, but I don't think it's all too important.

Would you be fine if I fix all occurences and change the level to `"error"` again?

**Comment by siemiatj** [comment]
Yeah, we can change the level to error. But double quotes are not used anywhere in any respectable project I know of. I used the settings that facebook enforces for React and all of it's projects as this is now the de facto standard. Especially that some of the files written earlier are using different standards anyways.

**Comment by teosarca** [comment]
i also think we shall do 1 commit to convert to current rules.
This would ease reviewing future PRs because they will not be "polluted" with prettier fixes.
wdyt?

**Comment by PabloSichert** [comment]
Jup, doing that right now

**Comment by PabloSichert** [comment]
> Especially that some of the files written earlier are using different standards anyways.

That's probably just because there was no `yarn lint --fix` applied after your changes and things have been inconsistent.

Should be in check again with https://github.com/metasfresh/metasfresh-webui-frontend/pull/1636

**Pull request merged**
