### PR TITLE
Code hygiene and optimizations

### PR DESCRIPTION
**Pull request by PabloSichert**
Changed the naming consistently:
- Callback properties being passed down to child components: `on*`
- Event handlers: `handle*`
- `tabid` -> `tabId`
- `rowid` -> `rowId`

Rewrote a lot of arrow functions into class members so that function objects keep the same when passing them down to child components, saving re-renders

### CODE REVIEW

**Comment by siemiatj** [comment]
I like those changes but are you sure everything was carried over ? I can't find some of the action creators/api calls.

**Comment by PabloSichert** [comment]
> are you sure everything was carried over ? I can't find some of the action creators/api calls.

No, not with complete certainty. Could you point me to where you suspect something could break so I can check?

Unrelated: Working right now on at least adding the prop types Codacy complains about

**Comment by PabloSichert** [comment]
> I think to stay on the safe side (and not introduce merge conflicts) it'd be wiser to gradually include changes from this PR, either by cherry-picking commits or just copy/pasting what's there while working on related components.

That won't be possible since the dependencies on renaming are very intertwined here.

> I'm kinda scared to merge it as it is to be honest ;)

I understand the concerns, this could break functionality temporarily.

On the upside: Those errors will be really easy to fix (just renaming). Obviously merging this on a Friday is a bad idea. If we merge it on Monday we can work through the obvious errors and have the code tidied up with this PR.

P.S.:
Codacy doesn't seem to recognize some fixed prop types

**Comment by PabloSichert** [comment]
@siemiatj do you want me to complete this PR?

Otherwise I'll just close this as I won't be working regurarly on metasfresh any more

**Comment by siemiatj** [comment]
You can leave it as it is. I'll start gradually cherry-picking commits from this PR into master.

**Comment by teosarca** [comment]
closing this PR because i don't think somebody will use it

**Comment by siemiatj** [comment]
I am using this when doing my changes. The basic idea was good, but execution was not :)

**Pull request closed without merging**
