### PR TITLE
Fix auto focus for List inputs in modal and selecting first option on the list

### PR DESCRIPTION
**Pull request by siemiatj**
Param name was wrong. I'm not sure how this was working before but this solves #1554 . Also refactored List and RawList components, decoupling them, extracting some code to a separate function (which will make this easier to test) and moving focus/toggle control to parent component. Now it should be easier to debug and understand what's going on when events are not flying around like crazy.
This also changes how select fields behave when selected with keyboard. No by default they are focused (which a visual indication) first and require user to click arrow down to show the list. Lookup fields work as before.

### CODE REVIEW

**Comment by siemiatj** [comment]
Don't look at codeclimate. Nothing interesting there.

**Comment by metas-mk** [comment]
Checked locally. Using keyboard only in the first step.

- In Picking modal overlay, Choose ```alt+l``` to open the quickaction list. select ```Pick to new HU```.
image

- Next thing the user sees is a focussed List widget (OK) but the dropdown list is expanded. I believe it shall be focused but collapsed for such kind of action parms. The user can press ```space``` to expand. Also when expanding the dropdown the first entry shall be visible selected initially.
image

- After selecting an entry, confirming with ```enter```, the same dropdown list was opened another time. Shall not be.

@siemiatj pls ping me if we shall discuss the options.

**Comment by siemiatj** [comment]
I think selecting the first element in dropdown is covered by : https://github.com/metasfresh/metasfresh-webui-frontend/issues/1550

**Comment by metas-mk** [comment]
Checked locally. Boxes around lookup widgets are missing. NOK
image

Dropdown lists are now not opening automatically when focused. Arrow down has to be pressed. OK

Dropdown in first Parm of action menu is still opening automatically. NOK
image

**Comment by metas-mk** [comment]
Checked locally. Works as required. Minor issues found but will be addressed in follow-up issues.

**Pull request merged**
