### PR TITLE
Fix data sent with process requests

### PR DESCRIPTION
**Pull request by siemiatj**
Related to #2199

### CODE REVIEW

**Comment by teosarca** [comment]
quickly checked, but still not working:

image

image


image

**Comment by siemiatj** [comment]
it'd be awesome to get a spec for modals at one point. There's a lot of ifs and different cases there which I don't have enough familiarity with.

screen shot 2019-03-01 at 13 25 15

**Comment by teosarca** [comment]
quick tested, looks good

**Comment by metas-ts** [comment]
🍒 picked the 3 commits of PR https://github.com/metasfresh/metasfresh-webui-frontend/pull/2200 into the `release` branch

**Pull request merged**
