### PR TITLE
Fix saving location changes

### PR DESCRIPTION
**Pull request by siemiatj**
Our current logic for handling showing/hiding/submitting of widgets is terrible. Here's a major rewrite relying less on savingstates in variables and switching between focused/blurred states.

For now I tested it in window 123 & 143 and looks to be working fine. ~Still need to add some tests.~

I'll add tests in a separate PR as it requires quite a bit of plumbing before.

### CODE REVIEW

**Comment by siemiatj** [comment]
Jesus both codeclimate and codebeat are just useless...

**Comment by metas-ts** [comment]
this PR belongs to #1598

**Comment by metas-ts** [comment]
hi @siemiatj 

> Jesus both codeclimate and codebeat are just useless...

when writing java, codeclimate usually fails alltogether (probably the repo is too big)..codebeat "often" shows a result, but would need a lot of tuning to get rid of many false positives..
So they are not super useful to me either, but i often take at least a glimpse at them..

Having that said, if they annoy you in metasfresh-webui-frontend, we can kick them out.

**Comment by metas-mk** [comment]
Checked locally. Found minor glitches but fixes the described. Merging.

**Comment by siemiatj** [comment]
@metas-mk can you roughly describe the glitches ? I'm trying to write tests for those components so maybe we could write a test case covering this.

**Comment by metas-mk** [comment]
@siemiatj yes, just minor one(s)
- Open the window/123/ and add a new location
- press on ```edit``` button for location
- don't record anything, instead press on space outside or inside modal
- a message appears ```Do you really want to leave?```. press OK.
- the locator edit closes.

I think that the user should not get the question ```Do you really want to leave?``` just when pressing outside/ inside modal with locator editor opened. The locator editor should just close without content.

**Comment by siemiatj** [comment]
Oh, cool. Yeah, it was weird to me too, but I thought it's intentional. This'll be a quick fix.

**Pull request merged**
